V2 add comgate gateway
sinfin/boutique pull request #21
Opened 2023-04-26 19:49 UTC by foton

Přidání druhé  platební brány (Comgate skrz `comgate_ruby` gem).
 To si vynutilo
1) vytvoření `Boutique::GoPay::UniversalGateway`, která má stejné rozhraní jako `Comgate::Gateway` a volá `GoPay::Gateway` metody.
2) vytvoření `Boutique::PaymentGateway`, která převádí parametry typu `order`, `payment` atd na "standardizovaný" hash pro brány z bodu 1. Také vybírá při `Boutique::PaymentGateway.new(:comgate)` bránu z těch přednastavených v `Boutique.config.payment_gateways`.
3) upravena všechna původní volání GoPay na cally `Boutique::PaymentGateway`, popř `order.payment_gateway` (pro případ budoucího přepínání bran za běhu).
4) původní `go_pay_controller` předělán na univerzální `payment_gateways_controller.rb` schopný zpracovat zpětná volání a comebacky z různých bran

2023-04-27 12:05 UTC, foton commented
Cvičné karty pro GoPay https://help.gopay.com/cs/tema/integrace-platebni-brany/technicky-popis-integrace-platebni-brany/provadeni-plateb-v-testovacim-prostredi

2023-05-02 08:02 UTC, dedekm requested changes
@foton 2 drobnosti ale jinak super, diky

2023-05-03 13:08 UTC, foton commented on lib/boutique/config.rb
> +                                                    client_secret: ENV.fetch("GO_PAY_CLIENT_SECRET")), # client authorization secret (password)
A kde to nastavuješ ? V `/home/foton/workspace/boutique/test/dummy/config/initializers/payment_gateways.rb` ? Nebo v tom `lib/boutique/config.rb` .  Asi je hloupost mít to v defaultním configu, nechám ho prázdný.

2023-05-03 13:16 UTC, foton commented on lib/boutique/config.rb
> +                                                    client_secret: ENV.fetch("GO_PAY_CLIENT_SECRET")), # client authorization secret (password)
Refactorováno. Zrušen implicitní GoPay  v configu, brány je nutné stavit v `config/initializers`

2023-05-03 13:22 UTC, foton commented on app/lib/boutique/go_pay/gopay_ruby_override.rb
Tohle už je snad taky OK. Klasická neshoda předpokládané konstanty odvozené z jména souboru.

2023-05-03 13:23 UTC, foton commented
@dedekm  Opraveno, zkus to teď.

2023-05-09 16:59 UTC, dedekm approved these changes
@foton pull request mergnu ale bude jeste potreba doladit ten callback, aktualne se stav platby bere jen z parametru, takze to funguje ale je to bezpecnostni dira, logicky si to musi vzit jen id a udelat status check pres api

viz https://apidoc.comgate.cz/?lang=cs#p%C5%99esm%C4%9Brov%C3%A1n%C3%AD-pl%C3%A1tce-na-web-klienta
> Pokud se platební brána dozví výsledek platby okamžitě po provedení platby Plátcem, pak je Plátce směrován na příslušné URL (PAID nebo CANCELLED). Jestliže eshop implementoval předávání výsledku platby na pozadí, pak se přesměrování na web Klienta provede až po úspěšném předání výsledku platby na pozadí. Plátci nelze odeslat zboží nebo službu, kterou objednal, pouze na základě URL použité pro přesměrování, protože Plátce by mohl výsledek platby podvrhnout změnou URL ve webovém prohlížeči.

2023-05-09 16:59 UTC, merged